# Konfigurasi Netlify — JAYARAYA
[build]
  publish = "."
  functions = "netlify/functions"

# (opsional) header keamanan dasar
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
